# 1.what is numpy?

In [27]:
#2.how to import numpy?
import numpy as np

In [29]:
# 3.create a 1-D numpy array?
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [31]:
#4. create a 2- D numpy array?
b=np.array([[1,2,3,4],[5,6,7,8]])
b




array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
#5. create a 2-D numpy array?
c=np.array([[[5,6,7,8],[1,2,3,4]],[[9,10,11,12],[13,14,15,16]]])
c

array([[[ 5,  6,  7,  8],
        [ 1,  2,  3,  4]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [35]:
#6. what is the shape of an array?
print(a.shape)

(4,)


In [37]:
print(b.shape)

(2, 4)


In [39]:
print(c.shape)

(2, 2, 4)


In [41]:
# 7.how to create all zeros?
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
# 8.how to create all ones?
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
#9. how to check numpy data array?
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:")
print(arr)

print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Data type:", arr.dtype)
print("Total elements:", arr.size)
print("Object type:", type(arr))


Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2
Data type: int32
Total elements: 6
Object type: <class 'numpy.ndarray'>


In [47]:
#10. how to create a range of numbers ?create random numbers ?
import numpy as np
#1
arr = np.arange(0, 10, 2)  # Start at 0, stop before 10, step by 2
print(arr)
#2
arr = np.linspace(0, 1, 5)  # 5 numbers between 0 and 1
print(arr)
#3
rand_int = np.random.randint(1, 10, size=(3, 3))  # 3x3 array of ints from 1 to 9
print(rand_int)


[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[5 8 3]
 [7 4 7]
 [8 8 8]]


In [ ]:
# how to install numpy?
